# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
