# Generated by Django 2.2.5 on 2019-09-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_app', '0003_auto_20190926_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='party_app.Event'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_post', to='party_app.User'),
        ),
    ]
